jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: VarunBhardwaj1/BillSplit.github.io
          ref: main
          path: source

      - name: Check contents of source folder
        run: ls -la source

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd source
          npm install --no-package-lock

      - name: Build project
        run: |
          cd source
          npm run build
